-- MySQL Script generated by MySQL Workbench
-- qua 12 set 2018 21:48:37 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema data_form
-- -----------------------------------------------------
SET NAMES 'utf8';
SET character_set_connection=utf8;
SET character_set_client=utf8;
SET character_set_results=utf8;
-- -----------------------------------------------------
-- Schema data_form
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `data_form` DEFAULT CHARACTER SET utf8 ;
USE `data_form` ;
-- -----------------------------------------------------
-- Table `data_form`.`TB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_form`.`TB_USUARIO` (
  `CD_USUARIO` INT AUTO_INCREMENT,
  `NM_USUARIO` VARCHAR(100) NOT NULL,
  `DS_EMAIL` VARCHAR(45) NOT NULL,
  `DT_NASCIMENTO` DATE NOT NULL,
  `DS_SENHA` VARCHAR(45) NOT NULL,
  `DS_EMAIL_RECUPERACAO` VARCHAR(45) NOT NULL,
  `IMG_USUARIO` VARCHAR(150) NULL,
  PRIMARY KEY (`CD_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_form`.`TB_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_form`.`TB_CATEGORIA` (
  `CD_CATEGORIA` INT AUTO_INCREMENT,
  `NM_CATEGORIA` VARCHAR(45) NULL,
  PRIMARY KEY (`CD_CATEGORIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_form`.`TB_FORMULARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_form`.`TB_FORMULARIO` (
  `CD_FORMULARIO` INT AUTO_INCREMENT,
  `NM_FORMULARIO` VARCHAR(45) NOT NULL,
  `DT_ABERTURA_FORM` DATE NULL,
  `DT_FECHAMENTO_FORM` VARCHAR(45) NULL,
  `ID_USUARIO` INT NOT NULL,
  `ID_CATEGORIA` INT NOT NULL,
  `DS_FORMULARIO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CD_FORMULARIO`),
  INDEX `fk_TB_FORMULARIO_TB_USUARIO_idx` (`ID_USUARIO` ASC),
  INDEX `fk_TB_FORMULARIO_TB_CATEGORIA1_idx` (`ID_CATEGORIA` ASC),
  CONSTRAINT `fk_TB_FORMULARIO_TB_USUARIO`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `data_form`.`TB_USUARIO` (`CD_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_FORMULARIO_TB_CATEGORIA1`
    FOREIGN KEY (`ID_CATEGORIA`)
    REFERENCES `data_form`.`TB_CATEGORIA` (`CD_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_form`.`TB_TIPO_PERGUNTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_form`.`TB_TIPO_PERGUNTA` (
  `CD_TIPO_PERGUNTA` INT AUTO_INCREMENT,
  `NM_TIPO_PERGUNTA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CD_TIPO_PERGUNTA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_form`.`TB_PERGUNTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_form`.`TB_PERGUNTA` (
  `CD_PERGUNTA` INT AUTO_INCREMENT,
  `NM_PERGUNTA` VARCHAR(200) NOT NULL,
  `ID_TIPO_PERGUNTA` INT NOT NULL,
  `ID_FORMULARIO` INT NOT NULL,
  PRIMARY KEY (`CD_PERGUNTA`),
  INDEX `fk_TB_PERGUNTA_TB_TIPO_PERGUNTA1_idx` (`ID_TIPO_PERGUNTA` ASC),
  INDEX `fk_TB_PERGUNTA_TB_FORMULARIO1_idx` (`ID_FORMULARIO` ASC),
  CONSTRAINT `fk_TB_PERGUNTA_TB_TIPO_PERGUNTA1`
    FOREIGN KEY (`ID_TIPO_PERGUNTA`)
    REFERENCES `data_form`.`TB_TIPO_PERGUNTA` (`CD_TIPO_PERGUNTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_PERGUNTA_TB_FORMULARIO1`
    FOREIGN KEY (`ID_FORMULARIO`)
    REFERENCES `data_form`.`TB_FORMULARIO` (`CD_FORMULARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_form`.`TB_ALTERNATIVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_form`.`TB_ALTERNATIVA` (
  `CD_ALTERNATIVA` INT AUTO_INCREMENT,
  `NM_ALTERNATIVA` VARCHAR(45) NOT NULL,
  `ID_PERGUNTA` INT NOT NULL,
  PRIMARY KEY (`CD_ALTERNATIVA`),
  INDEX `fk_TB_ALTERNATIVA_TB_PERGUNTA1_idx` (`ID_PERGUNTA` ASC),
  CONSTRAINT `fk_TB_ALTERNATIVA_TB_PERGUNTA1`
    FOREIGN KEY (`ID_PERGUNTA`)
    REFERENCES `data_form`.`TB_PERGUNTA` (`CD_PERGUNTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data_form`.`TB_RESPOSTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data_form`.`TB_RESPOSTA` (
  `CD_RESPOSTA` INT AUTO_INCREMENT,
  `ID_ALTERNATIVA` INT NOT NULL,
  PRIMARY KEY (`CD_RESPOSTA`),
  INDEX `fk_TB_RESPOSTA_TB_ALTERNATIVA1_idx` (`ID_ALTERNATIVA` ASC),
  CONSTRAINT `fk_TB_RESPOSTA_TB_ALTERNATIVA1`
    FOREIGN KEY (`ID_ALTERNATIVA`)
    REFERENCES `data_form`.`TB_ALTERNATIVA` (`CD_ALTERNATIVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
